trigger:
  branches:
    include:
      - main  # Le pipeline se déclenche automatiquement sur chaque push vers la branche "main".

pool:
  name: Default  # Remplacez par le nom de votre pool si vous utilisez un agent auto-hébergé.

variables:
  # Variable secrète pour le Deploy Hook URL (assurez-vous de l'ajouter dans Azure DevOps comme variable secrète).
  RENDER_DEPLOY_HOOK_URL: $(RENDER_DEPLOY_HOOK_URL)

steps:
# Étape 1 : Récupérer le code source
- checkout: self
  fetchDepth: 1

# Étape 2 : Construire et pousser l'image Docker vers Docker Hub
- task: Docker@2
  inputs:
    containerRegistry: 'az-dockerhub-connection'  # Nom de votre connexion Docker Hub dans Azure DevOps.
    repository: 'hibaallah2024/docker-image'      # Chemin vers votre dépôt Docker Hub (ex: <utilisateur>/<nom-depot>).
    command: 'buildAndPush'                       # Construire et pousser l'image Docker.
    Dockerfile: 'Dockerfile'                      # Chemin relatif vers le Dockerfile.
    tags: 'latest'                                # Tag à utiliser pour l'image (ex: "latest").

# Étape 3 : Déclencher le déploiement sur Render via le Deploy Hook
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      curl -X POST "$(RENDER_DEPLOY_HOOK_URL)"
  displayName: 'Trigger Deploy via Render Hook'
