trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Replace with your self-hosted agent pool name if needed.

steps:
- checkout: self
  fetchDepth: 1

- task: Docker@2
  inputs:
    containerRegistry: 'az-dockerhub-connection'  # Replace with your Docker registry connection.
    repository: 'kawtark413/az-cicd'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- powershell: |
    curl.exe -X POST -H "Authorization: Bearer $env:RENDER_API_KEY" `
    -H "Content-Type: application/json" `
    -d '{\"serviceId\":\"az-cicd\",\"clearCache\":true}' `
    "https://api.render.com/v1/services/az-cicd/deploy"
  displayName: 'Trigger Deploy on Render'


